from enum import Enum

class BasketBall(Enum):
    POINTS = 1
    REBOUNDS = 2
    ASSISTS = 3
    POINTS_REBOUNDS_ASSISTS = 4
    FANTASY_SCORE = 5
    THREES_MADE = 6
    DEF_REBOUNDS = 7
    OFF_REBOUNDS = 8
    THREES_ATTEMPTED = 9
    POINTS_COMBO = 10
    ASSISTS_COMBO = 11
    REBOUNDS_COMBO = 12
    THREES_MADE_COMBO = 13
    FREETHROWS_MADE = 14
    FG_ATTEMPTED = 15
    POINTS_REBOUNDS = 16
    DUNKS = 17
    BLOCKED_SHOTS = 18
    STEALS = 19
    REBOUNDS_ASSISTS = 20
    BLOCKS_STEALS = 21
    TURNOVERS = 22
